# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('link', models.CharField(max_length=360)),
                ('pubdate', models.DateTimeField()),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(max_length=60)),
                ('tags', models.CharField(blank=True, max_length=180)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('keywords', models.ManyToManyField(blank=True, to='Classifier.Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('keywords', models.ManyToManyField(blank=True, to='Classifier.Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Classifier.Article')),
                ('keywords', models.ManyToManyField(blank=True, to='Classifier.Keywords')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Classifier.Article')),
                ('organization', models.ManyToManyField(blank=True, to='Classifier.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedPersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Classifier.Article')),
                ('person', models.ManyToManyField(blank=True, to='Classifier.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(max_length=300)),
            ],
        ),
    ]
