# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Classifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
    ]
